In [1]:
import os
import numpy as np

In [10]:
data_file = "labapp3-data-new.txt"
f = open(data_file, "r").read()
print(f[:100])

0 NaN NaN NaN NaN NaN
30 19 19.7336 37.0933 71.76 2.69964
30 25 19.616 37.5737 97.52 2.69964
30 24 1


In [11]:
# data attributes
#time nodeid temperature humidity light voltage

In [13]:
from tqdm import tqdm

data = f.split("\n")
X = []

for i in tqdm(data):
    try:
        X.append([float(x) for x in i.split(" ")])
        # check if list has nan values
        if np.isnan(X[-1]).any():
            X.pop()
    except:
        print("error")
        print(i)
X[:10]


100%|██████████| 2313683/2313683 [00:14<00:00, 162854.73it/s]

error



[[30.0, 19.0, 19.7336, 37.0933, 71.76, 2.69964],
 [30.0, 25.0, 19.616, 37.5737, 97.52, 2.69964],
 [30.0, 24.0, 19.7728, 37.162, 143.52, 2.71196],
 [30.0, 3.0, 20.204, 36.8871, 50.6, 2.69964],
 [30.0, 6.0, 20.4196, 36.6118, 121.44, 2.65143],
 [30.0, 26.0, 19.4494, 39.62, 121.44, 2.69964],
 [30.0, 27.0, 20.1354, 37.162, 79.12, 2.71196],
 [30.0, 31.0, 19.5572, 39.0763, 150.88, 2.69964],
 [30.0, 34.0, 19.4298, 39.0763, 60.72, 2.68742],
 [30.0, 43.0, 19.7532, 35.853, 478.4, 2.65143]]

In [25]:
temp = X[:10]
#get the last 4 values of this list normalized
MIN_S = np.min(np.array(temp), axis=0)
MAX_S = np.max(np.array(temp), axis=0)

print((np.array(temp[3])-MIN_S)/MAX_S)


[0.         0.         0.03791455 0.02610045 0.         0.01777681]


In [15]:
from collections import defaultdict
data_dict = defaultdict(dict)
for dt in tqdm(X):
    # check if dt has any nan value
    #if np.isnan(dt).any():
    if np.isnan(dt[1]):
        continue
    if int(dt[1]) in data_dict[int(dt[0])].keys():
        data_dict[int(dt[0])][int(dt[1])].append(dt[2:])
    else:
        data_dict[int(dt[0])][int(dt[1])] = dt[2:]



100%|██████████| 2219803/2219803 [00:08<00:00, 273310.67it/s]


In [27]:
data_dict[900]

{3: [19.3318, 38.9401, 48.76, 2.68742],
 29: [18.8222, 40.3652, 180.32, 2.67532],
 27: [19.1848, 39.3143, 79.12, 2.69964],
 42: [17.8912, 40.399, 478.4, 2.67532],
 18: [18.8712, 38.8379, 57.04, 2.50599],
 17: [18.6556, 39.5521, 32.2, 2.57108],
 4: [19.7336, 39.4842, 97.52, 2.65143],
 11: [18.5184, 41.7133, 861.12, 2.67532],
 45: [18.2342, 38.3263, 172.96, 2.67532],
 19: [18.9104, 38.872, 71.76, 2.68742],
 44: [17.6364, 40.6693, 97.52, 2.67532],
 40: [18.6458, 39.62, 172.96, 2.68742],
 22: [18.7144, 38.9742, 79.12, 2.67532],
 14: [17.7736, 41.8812, 28.52, 2.69964],
 43: [18.8222, 37.745, 456.32, 2.65143],
 46: [18.3028, 38.7357, 114.08, 2.47467],
 54: [15.8234, 46.2297, 41.4, 2.65143],
 21: [19.1456, 38.1213, 108.56, 2.69964],
 25: [18.3616, 40.0945, 97.52, 2.67532],
 8: [18.8124, 40.2976, 108.56, 2.68742],
 52: [17.5384, 40.568, 60.72, 2.65143],
 23: [19.3808, 38.1213, 224.48, 2.68742],
 20: [20.2432, 35.9912, 128.8, 3.14243],
 39: [19.0182, 39.6878, 150.88, 2.68742],
 47: [18.0676, 40

In [31]:
num_sensors = 3
adj_matrix = np.ones((num_sensors, num_sensors))
np.fill_diagonal(adj_matrix, 0)
temp = np.transpose(np.nonzero(adj_matrix)).reshape(1, -1)
edge_list = np.array([np.array(temp[0][::2]) , np.array(temp[0][1::2])])
for idx in range(edge_list.shape[1]):
    print(edge_list[0][idx], edge_list[1][idx])

0 1
0 2
1 0
1 2
2 0
2 1


In [34]:
positions = open('labapp3-positions.txt', 'r').read().strip()
positions = positions.split("\n")
positions = [x.split(" ") for x in positions]
print(positions)
positions = [[float(x) for x in data] for data in positions]
position = {}
for dt in positions:
    position[int(dt[0])] = (dt[1], dt[2])

[['1', '21.5', '23'], ['2', '24.5', '20'], ['3', '19.5', '19'], ['4', '22.5', '15'], ['5', '24.5', '12'], ['6', '19.5', '12'], ['7', '22.5', '8'], ['8', '24.5', '4'], ['9', '21.5', '2'], ['10', '19.5', '5'], ['11', '16.5', '3'], ['12', '13.5', '1'], ['13', '12.5', '5'], ['14', '8.5', '6'], ['15', '5.5', '3'], ['16', '1.5', '2'], ['17', '1.5', '8'], ['18', '5.5', '10'], ['19', '3.5', '13'], ['20', '0.5', '17'], ['21', '4.5', '18'], ['22', '1.5', '23'], ['23', '6', '24'], ['24', '1.5', '30'], ['25', '4.5', '30'], ['26', '7.5', '31'], ['27', '8.5', '26'], ['28', '10.5', '31'], ['29', '12.5', '26'], ['30', '13.5', '31'], ['31', '15.5', '28'], ['32', '17.5', '31'], ['33', '19.5', '26'], ['34', '21.5', '30'], ['35', '24.5', '27'], ['36', '26.5', '31'], ['37', '27.5', '26'], ['38', '30.5', '31'], ['39', '30.5', '26'], ['40', '33.5', '28'], ['41', '36.5', '30'], ['42', '39.5', '30'], ['43', '35.5', '24'], ['44', '40.5', '22'], ['45', '37.5', '19'], ['46', '34.5', '16'], ['47', '39.5', '14'], [

In [35]:
position

{1: (21.5, 23.0),
 2: (24.5, 20.0),
 3: (19.5, 19.0),
 4: (22.5, 15.0),
 5: (24.5, 12.0),
 6: (19.5, 12.0),
 7: (22.5, 8.0),
 8: (24.5, 4.0),
 9: (21.5, 2.0),
 10: (19.5, 5.0),
 11: (16.5, 3.0),
 12: (13.5, 1.0),
 13: (12.5, 5.0),
 14: (8.5, 6.0),
 15: (5.5, 3.0),
 16: (1.5, 2.0),
 17: (1.5, 8.0),
 18: (5.5, 10.0),
 19: (3.5, 13.0),
 20: (0.5, 17.0),
 21: (4.5, 18.0),
 22: (1.5, 23.0),
 23: (6.0, 24.0),
 24: (1.5, 30.0),
 25: (4.5, 30.0),
 26: (7.5, 31.0),
 27: (8.5, 26.0),
 28: (10.5, 31.0),
 29: (12.5, 26.0),
 30: (13.5, 31.0),
 31: (15.5, 28.0),
 32: (17.5, 31.0),
 33: (19.5, 26.0),
 34: (21.5, 30.0),
 35: (24.5, 27.0),
 36: (26.5, 31.0),
 37: (27.5, 26.0),
 38: (30.5, 31.0),
 39: (30.5, 26.0),
 40: (33.5, 28.0),
 41: (36.5, 30.0),
 42: (39.5, 30.0),
 43: (35.5, 24.0),
 44: (40.5, 22.0),
 45: (37.5, 19.0),
 46: (34.5, 16.0),
 47: (39.5, 14.0),
 48: (35.5, 10.0),
 49: (39.5, 6.0),
 50: (38.5, 1.0),
 51: (35.5, 4.0),
 52: (31.5, 6.0),
 53: (28.5, 5.0),
 54: (26.5, 2.0)}

In [39]:
np.array(list(data_dict[30].keys()))-1

array([18, 24, 23,  2,  5, 25, 26, 30, 33, 42, 19, 39])

In [91]:
from scipy.spatial.distance import cdist
adj = cdist(np.array(positions)[:, 1:], np.array(positions)[:, 1:], metric='euclidean')

In [92]:
adj.shape

(54, 54)

In [17]:
A = np.load(os.path.join("data/adj_mat.npy"))
X = np.load(os.path.join("data/node_values.npy")).transpose(
    (1, 2, 0)
)

In [29]:
X.shape 
#sensors, total outputs time



(207, 2, 34272)

In [85]:
our_x = np.zeros((54,len(list(data_dict.keys())), 4))

time_idx = {}
for idx, key in enumerate(data_dict.keys()):
    time_idx[key] = idx

In [102]:
from tqdm import tqdm
data = f.split("\n")

for i in tqdm(data):
    try:
        X = [float(x) for x in i.split(" ")]
        our_x[int(X[1])][time_idx[int(X[0]) -1]][0] = X[2]
        our_x[int(X[1])][time_idx[int(X[0]) -1]][1] = X[3]
        our_x[int(X[1])][time_idx[int(X[0]) -1]][2] = X[4]
        our_x[int(X[1])][time_idx[int(X[0]) -1]][3] = X[5]

    except:
        continue

100%|██████████| 2313683/2313683 [00:06<00:00, 355962.60it/s]


In [103]:
our_x.shape

(54, 4, 210800)

In [104]:
our_x = our_x.transpose(0, 2, 1)
our_x.shape

(54, 210800, 4)

In [105]:
# save numpy array to a file
from numpy import asarray
from numpy import save
# save to npy file
save('data/our_data.npy', our_x)
save('data/our_adj.npy', adj)


In [75]:
data_dict[30]

{25: [18.93, 38.8039, 97.52, 2.68742],
 30: [18.4596, 41.5789, 114.08, 2.68742],
 10: [19.273, 39.9252, 75.44, 2.67532],
 26: [18.8614, 40.9055, 121.44, 2.68742],
 31: [18.9496, 40.3652, 150.88, 2.69964],
 32: [18.734, 39.9929, 121.44, 2.69964],
 21: [19.5964, 37.162, 114.08, 2.69964]}

In [65]:
X = np.load(os.path.join("data/node_values.npy"))

In [74]:
X[200]

array([[67.        ,  0.69444444],
       [63.5       ,  0.69444444],
       [65.5       ,  0.69444444],
       [53.375     ,  0.69444444],
       [40.625     ,  0.69444444],
       [63.        ,  0.69444444],
       [31.625     ,  0.69444444],
       [62.25      ,  0.69444444],
       [65.375     ,  0.69444444],
       [68.375     ,  0.69444444],
       [62.625     ,  0.69444444],
       [62.625     ,  0.69444444],
       [15.        ,  0.69444444],
       [68.375     ,  0.69444444],
       [65.875     ,  0.69444444],
       [46.        ,  0.69444444],
       [19.375     ,  0.69444444],
       [56.375     ,  0.69444444],
       [57.25      ,  0.69444444],
       [47.        ,  0.69444444],
       [68.5       ,  0.69444444],
       [64.625     ,  0.69444444],
       [49.125     ,  0.69444444],
       [ 0.        ,  0.69444444],
       [54.125     ,  0.69444444],
       [ 0.        ,  0.69444444],
       [34.14285714,  0.69444444],
       [62.        ,  0.69444444],
       [68.375     ,

In [ ]:
# number of data * number of sensors * per sensor data 

In [61]:
import pandas as pd
from torch_geometric.data import Data
import numpy as np
import torch
import torch.nn as nn

from torch_geometric.nn import GCNConv
import torch.nn.functional as F
from tqdm import tqdm
import math
from torch_geometric.nn import GCNConv, GATv2Conv
from torch_geometric.loader import DataLoader
torch.manual_seed(12345)



positions = open('labapp3-positions.txt', 'r').read().strip()
positions = positions.split("\n")
positions = [x.split(" ") for x in positions]
#print(positions)
positions = [[float(x) for x in data] for data in positions]
position = {}
for dt in positions:
    position[int(dt[0])] = (dt[1], dt[2])

from tqdm import tqdm
data_file = "labapp3-data-new.txt"
f = open(data_file, "r").read()
data = f.split("\n")
X = []
for i in tqdm(data):
    try:
        X.append([float(x) for x in i.split(" ")])
        if np.isnan(X[-1]).any():
            X.pop()
    except:
        pass
MIN_S = np.min(np.array(X), axis=0)
MAX_S = np.max(np.array(X), axis=0)
num_sensors = 54
from collections import defaultdict
data_dict = defaultdict(dict)
for dt in tqdm(X):
    if np.isnan(dt[1]):
        continue
    if int(dt[1]) < num_sensors:
        data_dict[int(dt[0])][int(dt[1])] = dt[2:]

adj_matrix = np.ones((num_sensors, num_sensors))
np.fill_diagonal(adj_matrix, 0)
temp = np.transpose(np.nonzero(adj_matrix)).reshape(1, -1)
edge_list = np.array([np.array(temp[0][::2]) , np.array(temp[0][1::2])])
edge_attr = []
for idx in range(edge_list.shape[1]):
    fm, to = edge_list[0][idx]+1, edge_list[1][idx]+1
    edge_attr.append(math.sqrt((position[fm][0]-position[to][0])**2 + (position[fm][1]-position[to][1])**2))
edge_attr = np.array(edge_attr)


100%|██████████| 2219803/2219803 [00:07<00:00, 291090.75it/s]


In [62]:
graphs = []
for time in data_dict.keys():

    sensor_data = np.zeros((num_sensors, 4))
    for sensor_id in data_dict[time]:
        try:
            sensor_data[sensor_id-1] = (np.array(data_dict[time][sensor_id])-MIN_S[2:])/(MAX_S[2:]-MIN_S[2:])
        except:
            #print(np.array(data_dict[time][sensor_id]))
            #print(MIN_S[2:])
            continue

    g = Data(x=torch.tensor(sensor_data, dtype=torch.float), 
             edge_index=torch.tensor(edge_list,dtype=torch.long), 
             y=torch.tensor(sensor_data, dtype=torch.float),
             edge_attr=torch.tensor(edge_attr.reshape(-1, 1), dtype=torch.float))
             
    
    #g = Data(x=torch.rand((num_cols, num_cols), dtype=torch.float), edge_index=torch.tensor(edge_list,dtype=torch.long))
    
    #g.y = torch.tensor(np.array(sensor).reshape(-1, 1), dtype=torch.float)
    
    g.train_mask = np.array([False]*num_sensors)
    g.train_mask[np.array(list(data_dict[time].keys()))-1] = True
    g.train_mask = torch.tensor(g.train_mask)
    #print("train mask shape", g.train_mask.shape)
    #print("input shape",g.x.shape)

    g.test_mask = np.array(([True]*num_sensors))
    g.test_mask[np.array(list(data_dict[time].keys()))-1] = False
    g.test_mask = torch.tensor(g.test_mask)


KeyboardInterrupt: 

In [57]:
np.array(data_dict[258480])

array({22: [18.6066, 40.8043, 82.8, 2.61639], 44: [17.2444, 44.9121, 32.2, 2.63964], 23: [19.3024, 39.7217, 235.52, 2.65143], 10: [18.734, 42.685, 7.36, 2.63964], 31: [18.4106, 43.5522, 143.52, 2.65143], 26: [18.3714, 43.9844, 121.44, 2.65143], 29: [18.8418, 41.6461, 180.32, 2.65143], 25: [18.4988, 41.6461, 97.52, 2.65143], 19: [18.9104, 40.5004, 136.16, 2.65143], 41: [18.0872, 43.3525, 121.44, 2.63964], 24: [18.7438, 41.0404, 143.52, 2.67532], 7: [19.126, 41.0404, 9.2, 2.65143]},
      dtype=object)

In [45]:
sensor_data = np.zeros((num_sensors, 4))
print(sensor_data[53])
sensor_data[53] = np.array([1, 2, 3, 4])
print(sensor_data[53])

[0. 0. 0. 0.]
[1. 2. 3. 4.]
