In [1]:
import os
import numpy as np

In [10]:
data_file = "labapp3-data-new.txt"
f = open(data_file, "r").read()
print(f[:100])

0 NaN NaN NaN NaN NaN
30 19 19.7336 37.0933 71.76 2.69964
30 25 19.616 37.5737 97.52 2.69964
30 24 1


In [11]:
# data attributes
#time nodeid temperature humidity light voltage

In [13]:
from tqdm import tqdm

data = f.split("\n")
X = []

for i in tqdm(data):
    try:
        X.append([float(x) for x in i.split(" ")])
        # check if list has nan values
        if np.isnan(X[-1]).any():
            X.pop()
    except:
        print("error")
        print(i)
X[:10]


100%|██████████| 2313683/2313683 [00:14<00:00, 162854.73it/s]

error



[[30.0, 19.0, 19.7336, 37.0933, 71.76, 2.69964],
 [30.0, 25.0, 19.616, 37.5737, 97.52, 2.69964],
 [30.0, 24.0, 19.7728, 37.162, 143.52, 2.71196],
 [30.0, 3.0, 20.204, 36.8871, 50.6, 2.69964],
 [30.0, 6.0, 20.4196, 36.6118, 121.44, 2.65143],
 [30.0, 26.0, 19.4494, 39.62, 121.44, 2.69964],
 [30.0, 27.0, 20.1354, 37.162, 79.12, 2.71196],
 [30.0, 31.0, 19.5572, 39.0763, 150.88, 2.69964],
 [30.0, 34.0, 19.4298, 39.0763, 60.72, 2.68742],
 [30.0, 43.0, 19.7532, 35.853, 478.4, 2.65143]]

In [25]:
temp = X[:10]
#get the last 4 values of this list normalized
MIN_S = np.min(np.array(temp), axis=0)
MAX_S = np.max(np.array(temp), axis=0)

print((np.array(temp[3])-MIN_S)/MAX_S)


[0.         0.         0.03791455 0.02610045 0.         0.01777681]


In [15]:
from collections import defaultdict
data_dict = defaultdict(dict)
for dt in tqdm(X):
    # check if dt has any nan value
    #if np.isnan(dt).any():
    if np.isnan(dt[1]):
        continue
    if int(dt[1]) in data_dict[int(dt[0])].keys():
        data_dict[int(dt[0])][int(dt[1])].append(dt[2:])
    else:
        data_dict[int(dt[0])][int(dt[1])] = dt[2:]



100%|██████████| 2219803/2219803 [00:08<00:00, 273310.67it/s]


In [27]:
data_dict[900]

{3: [19.3318, 38.9401, 48.76, 2.68742],
 29: [18.8222, 40.3652, 180.32, 2.67532],
 27: [19.1848, 39.3143, 79.12, 2.69964],
 42: [17.8912, 40.399, 478.4, 2.67532],
 18: [18.8712, 38.8379, 57.04, 2.50599],
 17: [18.6556, 39.5521, 32.2, 2.57108],
 4: [19.7336, 39.4842, 97.52, 2.65143],
 11: [18.5184, 41.7133, 861.12, 2.67532],
 45: [18.2342, 38.3263, 172.96, 2.67532],
 19: [18.9104, 38.872, 71.76, 2.68742],
 44: [17.6364, 40.6693, 97.52, 2.67532],
 40: [18.6458, 39.62, 172.96, 2.68742],
 22: [18.7144, 38.9742, 79.12, 2.67532],
 14: [17.7736, 41.8812, 28.52, 2.69964],
 43: [18.8222, 37.745, 456.32, 2.65143],
 46: [18.3028, 38.7357, 114.08, 2.47467],
 54: [15.8234, 46.2297, 41.4, 2.65143],
 21: [19.1456, 38.1213, 108.56, 2.69964],
 25: [18.3616, 40.0945, 97.52, 2.67532],
 8: [18.8124, 40.2976, 108.56, 2.68742],
 52: [17.5384, 40.568, 60.72, 2.65143],
 23: [19.3808, 38.1213, 224.48, 2.68742],
 20: [20.2432, 35.9912, 128.8, 3.14243],
 39: [19.0182, 39.6878, 150.88, 2.68742],
 47: [18.0676, 40

In [31]:
num_sensors = 3
adj_matrix = np.ones((num_sensors, num_sensors))
np.fill_diagonal(adj_matrix, 0)
temp = np.transpose(np.nonzero(adj_matrix)).reshape(1, -1)
edge_list = np.array([np.array(temp[0][::2]) , np.array(temp[0][1::2])])
for idx in range(edge_list.shape[1]):
    print(edge_list[0][idx], edge_list[1][idx])

0 1
0 2
1 0
1 2
2 0
2 1


In [34]:
positions = open('labapp3-positions.txt', 'r').read().strip()
positions = positions.split("\n")
positions = [x.split(" ") for x in positions]
print(positions)
positions = [[float(x) for x in data] for data in positions]
position = {}
for dt in positions:
    position[int(dt[0])] = (dt[1], dt[2])

[['1', '21.5', '23'], ['2', '24.5', '20'], ['3', '19.5', '19'], ['4', '22.5', '15'], ['5', '24.5', '12'], ['6', '19.5', '12'], ['7', '22.5', '8'], ['8', '24.5', '4'], ['9', '21.5', '2'], ['10', '19.5', '5'], ['11', '16.5', '3'], ['12', '13.5', '1'], ['13', '12.5', '5'], ['14', '8.5', '6'], ['15', '5.5', '3'], ['16', '1.5', '2'], ['17', '1.5', '8'], ['18', '5.5', '10'], ['19', '3.5', '13'], ['20', '0.5', '17'], ['21', '4.5', '18'], ['22', '1.5', '23'], ['23', '6', '24'], ['24', '1.5', '30'], ['25', '4.5', '30'], ['26', '7.5', '31'], ['27', '8.5', '26'], ['28', '10.5', '31'], ['29', '12.5', '26'], ['30', '13.5', '31'], ['31', '15.5', '28'], ['32', '17.5', '31'], ['33', '19.5', '26'], ['34', '21.5', '30'], ['35', '24.5', '27'], ['36', '26.5', '31'], ['37', '27.5', '26'], ['38', '30.5', '31'], ['39', '30.5', '26'], ['40', '33.5', '28'], ['41', '36.5', '30'], ['42', '39.5', '30'], ['43', '35.5', '24'], ['44', '40.5', '22'], ['45', '37.5', '19'], ['46', '34.5', '16'], ['47', '39.5', '14'], [

In [35]:
position

{1: (21.5, 23.0),
 2: (24.5, 20.0),
 3: (19.5, 19.0),
 4: (22.5, 15.0),
 5: (24.5, 12.0),
 6: (19.5, 12.0),
 7: (22.5, 8.0),
 8: (24.5, 4.0),
 9: (21.5, 2.0),
 10: (19.5, 5.0),
 11: (16.5, 3.0),
 12: (13.5, 1.0),
 13: (12.5, 5.0),
 14: (8.5, 6.0),
 15: (5.5, 3.0),
 16: (1.5, 2.0),
 17: (1.5, 8.0),
 18: (5.5, 10.0),
 19: (3.5, 13.0),
 20: (0.5, 17.0),
 21: (4.5, 18.0),
 22: (1.5, 23.0),
 23: (6.0, 24.0),
 24: (1.5, 30.0),
 25: (4.5, 30.0),
 26: (7.5, 31.0),
 27: (8.5, 26.0),
 28: (10.5, 31.0),
 29: (12.5, 26.0),
 30: (13.5, 31.0),
 31: (15.5, 28.0),
 32: (17.5, 31.0),
 33: (19.5, 26.0),
 34: (21.5, 30.0),
 35: (24.5, 27.0),
 36: (26.5, 31.0),
 37: (27.5, 26.0),
 38: (30.5, 31.0),
 39: (30.5, 26.0),
 40: (33.5, 28.0),
 41: (36.5, 30.0),
 42: (39.5, 30.0),
 43: (35.5, 24.0),
 44: (40.5, 22.0),
 45: (37.5, 19.0),
 46: (34.5, 16.0),
 47: (39.5, 14.0),
 48: (35.5, 10.0),
 49: (39.5, 6.0),
 50: (38.5, 1.0),
 51: (35.5, 4.0),
 52: (31.5, 6.0),
 53: (28.5, 5.0),
 54: (26.5, 2.0)}

In [39]:
np.array(list(data_dict[30].keys()))-1

array([18, 24, 23,  2,  5, 25, 26, 30, 33, 42, 19, 39])

In [91]:
from scipy.spatial.distance import cdist
adj = cdist(np.array(positions)[:, 1:], np.array(positions)[:, 1:], metric='euclidean')

In [92]:
adj.shape

(54, 54)

In [17]:
A = np.load(os.path.join("data/adj_mat.npy"))
X = np.load(os.path.join("data/node_values.npy")).transpose(
    (1, 2, 0)
)

In [29]:
X.shape 
#sensors, total outputs time



(207, 2, 34272)

In [85]:
our_x = np.zeros((54,len(list(data_dict.keys())), 4))

time_idx = {}
for idx, key in enumerate(data_dict.keys()):
    time_idx[key] = idx

In [102]:
from tqdm import tqdm
data = f.split("\n")

for i in tqdm(data):
    try:
        X = [float(x) for x in i.split(" ")]
        our_x[int(X[1])][time_idx[int(X[0]) -1]][0] = X[2]
        our_x[int(X[1])][time_idx[int(X[0]) -1]][1] = X[3]
        our_x[int(X[1])][time_idx[int(X[0]) -1]][2] = X[4]
        our_x[int(X[1])][time_idx[int(X[0]) -1]][3] = X[5]

    except:
        continue

100%|██████████| 2313683/2313683 [00:06<00:00, 355962.60it/s]


In [103]:
our_x.shape

(54, 4, 210800)

In [104]:
our_x = our_x.transpose(0, 2, 1)
our_x.shape

(54, 210800, 4)

In [105]:
# save numpy array to a file
from numpy import asarray
from numpy import save
# save to npy file
save('data/our_data.npy', our_x)
save('data/our_adj.npy', adj)


In [75]:
data_dict[30]

{25: [18.93, 38.8039, 97.52, 2.68742],
 30: [18.4596, 41.5789, 114.08, 2.68742],
 10: [19.273, 39.9252, 75.44, 2.67532],
 26: [18.8614, 40.9055, 121.44, 2.68742],
 31: [18.9496, 40.3652, 150.88, 2.69964],
 32: [18.734, 39.9929, 121.44, 2.69964],
 21: [19.5964, 37.162, 114.08, 2.69964]}

In [65]:
X = np.load(os.path.join("data/node_values.npy"))

In [74]:
X[200]

array([[67.        ,  0.69444444],
       [63.5       ,  0.69444444],
       [65.5       ,  0.69444444],
       [53.375     ,  0.69444444],
       [40.625     ,  0.69444444],
       [63.        ,  0.69444444],
       [31.625     ,  0.69444444],
       [62.25      ,  0.69444444],
       [65.375     ,  0.69444444],
       [68.375     ,  0.69444444],
       [62.625     ,  0.69444444],
       [62.625     ,  0.69444444],
       [15.        ,  0.69444444],
       [68.375     ,  0.69444444],
       [65.875     ,  0.69444444],
       [46.        ,  0.69444444],
       [19.375     ,  0.69444444],
       [56.375     ,  0.69444444],
       [57.25      ,  0.69444444],
       [47.        ,  0.69444444],
       [68.5       ,  0.69444444],
       [64.625     ,  0.69444444],
       [49.125     ,  0.69444444],
       [ 0.        ,  0.69444444],
       [54.125     ,  0.69444444],
       [ 0.        ,  0.69444444],
       [34.14285714,  0.69444444],
       [62.        ,  0.69444444],
       [68.375     ,

In [ ]:
# number of data * number of sensors * per sensor data 

In [61]:
import pandas as pd
from torch_geometric.data import Data
import numpy as np
import torch
import torch.nn as nn

from torch_geometric.nn import GCNConv
import torch.nn.functional as F
from tqdm import tqdm
import math
from torch_geometric.nn import GCNConv, GATv2Conv
from torch_geometric.loader import DataLoader
torch.manual_seed(12345)



positions = open('labapp3-positions.txt', 'r').read().strip()
positions = positions.split("\n")
positions = [x.split(" ") for x in positions]
#print(positions)
positions = [[float(x) for x in data] for data in positions]
position = {}
for dt in positions:
    position[int(dt[0])] = (dt[1], dt[2])

from tqdm import tqdm
data_file = "labapp3-data-new.txt"
f = open(data_file, "r").read()
data = f.split("\n")
X = []
for i in tqdm(data):
    try:
        X.append([float(x) for x in i.split(" ")])
        if np.isnan(X[-1]).any():
            X.pop()
    except:
        pass
MIN_S = np.min(np.array(X), axis=0)
MAX_S = np.max(np.array(X), axis=0)
num_sensors = 54
from collections import defaultdict
data_dict = defaultdict(dict)
for dt in tqdm(X):
    if np.isnan(dt[1]):
        continue
    if int(dt[1]) < num_sensors:
        data_dict[int(dt[0])][int(dt[1])] = dt[2:]

adj_matrix = np.ones((num_sensors, num_sensors))
np.fill_diagonal(adj_matrix, 0)
temp = np.transpose(np.nonzero(adj_matrix)).reshape(1, -1)
edge_list = np.array([np.array(temp[0][::2]) , np.array(temp[0][1::2])])
edge_attr = []
for idx in range(edge_list.shape[1]):
    fm, to = edge_list[0][idx]+1, edge_list[1][idx]+1
    edge_attr.append(math.sqrt((position[fm][0]-position[to][0])**2 + (position[fm][1]-position[to][1])**2))
edge_attr = np.array(edge_attr)


100%|██████████| 2219803/2219803 [00:07<00:00, 291090.75it/s]


In [62]:
graphs = []
for time in data_dict.keys():

    sensor_data = np.zeros((num_sensors, 4))
    for sensor_id in data_dict[time]:
        try:
            sensor_data[sensor_id-1] = (np.array(data_dict[time][sensor_id])-MIN_S[2:])/(MAX_S[2:]-MIN_S[2:])
        except:
            #print(np.array(data_dict[time][sensor_id]))
            #print(MIN_S[2:])
            continue

    g = Data(x=torch.tensor(sensor_data, dtype=torch.float), 
             edge_index=torch.tensor(edge_list,dtype=torch.long), 
             y=torch.tensor(sensor_data, dtype=torch.float),
             edge_attr=torch.tensor(edge_attr.reshape(-1, 1), dtype=torch.float))
             
    
    #g = Data(x=torch.rand((num_cols, num_cols), dtype=torch.float), edge_index=torch.tensor(edge_list,dtype=torch.long))
    
    #g.y = torch.tensor(np.array(sensor).reshape(-1, 1), dtype=torch.float)
    
    g.train_mask = np.array([False]*num_sensors)
    g.train_mask[np.array(list(data_dict[time].keys()))-1] = True
    g.train_mask = torch.tensor(g.train_mask)
    #print("train mask shape", g.train_mask.shape)
    #print("input shape",g.x.shape)

    g.test_mask = np.array(([True]*num_sensors))
    g.test_mask[np.array(list(data_dict[time].keys()))-1] = False
    g.test_mask = torch.tensor(g.test_mask)


KeyboardInterrupt: 

In [57]:
np.array(data_dict[258480])

array({22: [18.6066, 40.8043, 82.8, 2.61639], 44: [17.2444, 44.9121, 32.2, 2.63964], 23: [19.3024, 39.7217, 235.52, 2.65143], 10: [18.734, 42.685, 7.36, 2.63964], 31: [18.4106, 43.5522, 143.52, 2.65143], 26: [18.3714, 43.9844, 121.44, 2.65143], 29: [18.8418, 41.6461, 180.32, 2.65143], 25: [18.4988, 41.6461, 97.52, 2.65143], 19: [18.9104, 40.5004, 136.16, 2.65143], 41: [18.0872, 43.3525, 121.44, 2.63964], 24: [18.7438, 41.0404, 143.52, 2.67532], 7: [19.126, 41.0404, 9.2, 2.65143]},
      dtype=object)

In [45]:
sensor_data = np.zeros((num_sensors, 4))
print(sensor_data[53])
sensor_data[53] = np.array([1, 2, 3, 4])
print(sensor_data[53])

[0. 0. 0. 0.]
[1. 2. 3. 4.]


In [89]:
import pandas as pd
from torch_geometric.data import Data
import numpy as np
import torch
import torch.nn as nn

from torch_geometric.nn import GCNConv
import torch.nn.functional as F
from tqdm import tqdm
import math
from torch_geometric.nn import GCNConv, GATv2Conv
from torch_geometric.loader import DataLoader
torch.manual_seed(12345)
df = pd.read_csv("df_env.csv")

df = df.dropna(how='all')
df = df.apply(lambda x: (x - x.min()) / (x.max() - x.min()))
df_list = df.values.tolist()
num_cols = 23
graphs = []
for sensor in df_list:

    updated_sensor = []
    for idx, val in enumerate(sensor):
        temp = [0]*num_cols
        if math.isnan(val):
            updated_sensor.append(temp[:])
            continue
        else:
            #print("comes", idx, val)
            temp[idx] = val
        #print(temp.shape)
        #print(temp)
        updated_sensor.append(temp[:])
    #if len(updated_sensor)==8:
    #    print(sensor)
    #    print(updated_sensor)
    #print("input shape",np.array(updated_sensor).shape)
    adj_matrix = np.ones((num_cols, num_cols))
    a = np.argwhere(np.isnan(sensor)).reshape(1, -1)[0]

    for idx in a:
        for i in range(num_cols):
            adj_matrix[idx][i] = 0
            adj_matrix[i][idx] = 0
    
    np.fill_diagonal(adj_matrix, 0)
    #if len(a):
    #    print(a)
    #    print(adj_matrix)
    temp = np.transpose(np.nonzero(adj_matrix)).reshape(1, -1)
    edge_list = np.array([np.array(temp[0][::2]) , np.array(temp[0][1::2])])
    g = Data(x=torch.tensor(np.array(updated_sensor), dtype=torch.float), edge_index=torch.tensor(edge_list,dtype=torch.long))
    #g = Data(x=torch.rand((num_cols, num_cols), dtype=torch.float), edge_index=torch.tensor(edge_list,dtype=torch.long))
    
    g.y = torch.tensor(np.array(sensor).reshape(-1, 1), dtype=torch.float)
    #g.y = torch.rand((num_cols, 1), dtype=torch.float)
    g.train_mask = np.array([True]*num_cols)
    g.train_mask[np.argwhere(np.isnan(sensor))] = False
    g.train_mask = torch.tensor(g.train_mask)
    #print("train mask shape", g.train_mask.shape)
    #print("input shape",g.x.shape)
    g.test_mask = np.array(([False]*num_cols))
    g.test_mask[np.argwhere(np.isnan(sensor))] = True
    g.test_mask = torch.tensor(g.test_mask)

    #replace g.x tensor with nan values to 0
    #print(g.x)
    #g.x[torch.isnan(g.x)] = 0
    #g.y[torch.isnan(g.x)] = 0
    #print(g.x.shape)
    graphs.append(g)

#graphs = graphs[:20]

#loader = DataLoader(graphs, batch_size=10, shuffle=False)

class GCN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = GCNConv(num_cols, 16)
        self.conv2 = GCNConv(16, 32)
        self.conv3 = GCNConv(32, 32)
        self.conv4 = GCNConv(32, 1)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index

        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        x = F.relu(x)
        x = self.conv3(x, edge_index)
        x = self.conv4(x, edge_index)
        x = torch.sigmoid(x)
        return x

class GAT(torch.nn.Module):
    """Graph Attention Network"""
    def __init__(self, dim_in=num_cols,dim_h=64, dim_out=1, heads=8):
        super().__init__()
        self.gat1 = GATv2Conv(dim_in, dim_h, heads=heads)
        self.bn1 = nn.BatchNorm1d(dim_h*heads)
        self.gats = nn.ModuleList(
            [
                GATv2Conv(dim_h*heads, dim_h*heads)
                for _ in range(2)
             ]
        )
        self.bn2s = nn.ModuleList(
            [
                nn.BatchNorm1d(dim_h*heads)
                for _ in range(2)
            ]
        )
        self.gat2 = GATv2Conv(dim_h*heads, dim_out, heads=1)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        #print(x.shape)
        h = self.gat1(x, edge_index)
        #print(h.shape)
        #h = self.bn1(h)
        h = F.relu(h)
        #print(h.shape)
        #for gat, bn in zip(self.gats, self.bn2s):
        #    h = gat(h, edge_index)
        #    h = bn(h)
        #    h = F.elu(h)
        #h = F.elu(h)

        h , att_weights = self.gat2(h, edge_index, return_attention_weights=True)
        #h = torch.sigmoid(h)
        #print(h.shape)
        return h, att_weights


class GAT_V2(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.gat1 = GATv2Conv(num_cols, 120, heads=8)
        self.gat2 = GATv2Conv(120*8, 1, heads=1)
        #self.conv1 = GCNConv(data.num_node_features, 120)
        #self.linear = nn.Linear(120, 5)
        #self.sigmoid = nn.Sigmoid()

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = self.gat1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x)
        x = self.gat2(x, edge_index) 
        #logits, attention_weights = x
        return x

def train_node_classifier(model, graphs, optimizer, criterion, n_epochs=100):

    for epoch in tqdm(range(1, n_epochs + 1)):
        total_loss = 0

        for graph in tqdm(graphs):
            model.train()
            optimizer.zero_grad()
            #print("before comes", graph.x.shape, graph.y.shape, graph.train_mask.shape, graph.edge_index)
            out = model(graph)
            #print("comes", graph.x.shape,out.shape, graph.y.shape, graph.train_mask.shape)
            loss = criterion(out[graph.train_mask] , graph.y[graph.train_mask])
            #print(loss)
            if math.isnan(loss.item()):
                print(epoch,graph.train_mask, out[graph.train_mask], graph.y[graph.train_mask], criterion(out[graph.train_mask], graph.y[graph.train_mask]))
                print("######### SHOULD NOT HAPPEN ######### ", loss)
                break
                #print(graph.x, graph.train_mask)
            #print(loss)
            total_loss+=loss.item()
            loss.backward()
            optimizer.step()
        
        print(f'Epoch: {epoch:03d}, Train Loss: {total_loss:.3f}')

    return model
model = GAT_V2().to('cpu')
#optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-4)

#criterion = nn.CrossEntropyLoss()
#criterion = nn.L1Loss()
#criterion = nn.BCEWithLogitsLoss()
#criterion = nn.BCELoss()
criterion = nn.MSELoss()
model = train_node_classifier(model, graphs, optimizer, criterion, n_epochs=5)


 20%|██        | 1/5 [00:31<02:05, 31.30s/it]

Epoch: 001, Train Loss: 245.847


 40%|████      | 2/5 [01:11<01:49, 36.62s/it]

Epoch: 002, Train Loss: 241.445


 60%|██████    | 3/5 [01:51<01:16, 38.02s/it]

Epoch: 003, Train Loss: 240.438


 80%|████████  | 4/5 [02:34<00:40, 40.14s/it]

Epoch: 004, Train Loss: 239.735


100%|██████████| 5/5 [03:24<00:00, 40.84s/it]

Epoch: 005, Train Loss: 239.350


In [90]:
print(graphs[4].y)
print(graphs[4].train_mask)
print(graphs[4].test_mask)

tensor([[0.8058],
        [   nan],
        [   nan],
        [0.8031],
        [   nan],
        [   nan],
        [0.2350],
        [   nan],
        [   nan],
        [0.2350],
        [   nan],
        [   nan],
        [0.2621],
        [   nan],
        [   nan],
        [0.2621],
        [   nan],
        [   nan],
        [0.9325],
        [   nan],
        [   nan],
        [0.9325],
        [   nan]])
tensor([ True, False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False, False,  True, False, False,  True, False,
        False,  True, False])
tensor([False,  True,  True, False,  True,  True, False,  True,  True, False,
         True,  True, False,  True,  True, False,  True,  True, False,  True,
         True, False,  True])


In [99]:
out_final = []
def eval_node_classifier(model, graphs):
    model.eval()
    with torch.no_grad():
        for idx, graph in tqdm(enumerate(graphs)):
            out = model(graph)
            # copy the output to a new list
            out_list = graph.y.clone()
            
            out_list[graph.test_mask] = out[graph.test_mask]
            out_list = out_list.reshape(1, -1)[0].detach().numpy().tolist()
            out_final.append(out_list)

eval_node_classifier(model, graphs)

# save out_final to csv with column names
mod_df = pd.DataFrame(out_final, columns=df.columns)
mod_df.to_csv('modified_env.csv', index=False)


3593it [00:13, 266.44it/s]


In [102]:
graphs[4].y

tensor([[0.8058],
        [   nan],
        [   nan],
        [0.8031],
        [   nan],
        [   nan],
        [0.2350],
        [   nan],
        [   nan],
        [0.2350],
        [   nan],
        [   nan],
        [0.2621],
        [   nan],
        [   nan],
        [0.2621],
        [   nan],
        [   nan],
        [0.9325],
        [   nan],
        [   nan],
        [0.9325],
        [   nan]])

In [98]:
df.columns

Index(['mean.Temperature_60', 'grad.Temperature_60', 'sd.Temperature_60',
       'mean.Temperature_480', 'grad.Temperature_480', 'sd.Temperature_480',
       'mean.Humidity_60', 'grad.Humidity_60', 'sd.Humidity_60',
       'mean.Humidity_480', 'grad.Humidity_480', 'sd.Humidity_480',
       'mean.Winvel_60', 'grad.Winvel_60', 'sd.Winvel_60', 'mean.Winvel_480',
       'grad.Winvel_480', 'sd.Winvel_480', 'mean.Solar_60', 'grad.Solar_60',
       'sd.Solar_60', 'mean.Solar_480', 'grad.Solar_480'],
      dtype='object')

In [100]:
print(out_final[4])
print(graphs[4].y)

[0.805787980556488, 0.3065623939037323, 0.2926788330078125, 0.8030948042869568, 0.3040156364440918, 0.2632540762424469, 0.23497267067432404, 0.29013514518737793, 0.26361241936683655, 0.23497267067432404, 0.30663588643074036, 0.2609925866127014, 0.26213592290878296, 0.26588839292526245, 0.3064268231391907, 0.26213592290878296, 0.24456262588500977, 0.25844889879226685, 0.9325337409973145, 0.27355900406837463, 0.24704766273498535, 0.9325337409973145, 0.2800537645816803]
tensor([[0.8058],
        [   nan],
        [   nan],
        [0.8031],
        [   nan],
        [   nan],
        [0.2350],
        [   nan],
        [   nan],
        [0.2350],
        [   nan],
        [   nan],
        [0.2621],
        [   nan],
        [   nan],
        [0.2621],
        [   nan],
        [   nan],
        [0.9325],
        [   nan],
        [   nan],
        [0.9325],
        [   nan]])


In [88]:
with torch.no_grad():
    for idx,  graph in enumerate(graphs):
        
        #check if test mask contains true
        if graph.test_mask.any():
            print(idx, graph.y, graph.test_mask)
            break
            

4 tensor([[0.8058],
        [0.2858],
        [0.2903],
        [0.8031],
        [0.3068],
        [0.2899],
        [0.2350],
        [0.3041],
        [0.2852],
        [0.2350],
        [0.2635],
        [0.3040],
        [0.2621],
        [0.2634],
        [0.2878],
        [0.2621],
        [0.3069],
        [0.3042],
        [0.9325],
        [0.2903],
        [0.3045],
        [0.9325],
        [0.2712]], grad_fn=<IndexPutBackward0>) tensor([False,  True,  True, False,  True,  True, False,  True,  True, False,
         True,  True, False,  True,  True, False,  True,  True, False,  True,
         True, False,  True])


In [83]:
graphs[4].y

tensor([[0.8273],
        [0.6343],
        [0.2725],
        [0.8229],
        [0.6272],
        [0.1574],
        [0.2268],
        [0.6690],
        [0.0384],
        [0.2274],
        [0.7108],
        [0.0379],
        [0.1917],
        [0.5438],
        [0.3401],
        [0.1916],
        [0.5475],
        [0.4264],
        [0.9454],
        [0.5079],
        [0.0254],
        [0.9448],
        [0.5074]], grad_fn=<IndexPutBackward0>)

In [40]:
import pandas as pd
from torch_geometric.data import Data
import numpy as np
import torch
import torch.nn as nn

from torch_geometric.nn import GCNConv
import torch.nn.functional as F
from tqdm import tqdm
import math
from torch_geometric.nn import GCNConv, GATv2Conv
from torch_geometric.loader import DataLoader
import copy
from tqdm import tqdm
torch.manual_seed(12345)


### distance matrix calculation for using in the graph

positions = open('labapp3-positions.txt', 'r').read().strip()
positions = positions.split("\n")
positions = [x.split(" ") for x in positions]
positions = [[float(x) for x in data] for data in positions]
position = {}
for dt in positions:
    position[int(dt[0])] = (dt[1], dt[2])

# reading the main data file for processing
data_file = "labapp3-data-new.txt"
f = open(data_file, "r").read()
data = f.split("\n")
X = []
for i in tqdm(data):
    try:
        X.append([float(x) for x in i.split(" ")])
        if np.isnan(X[-1]).any():
            X.pop()
    except:
        pass

# MAX MIN array calculation for each column for normalizing the data later

MIN_S = np.min(np.array(X), axis=0)
MAX_S = np.max(np.array(X), axis=0)


#creating a dictionary of data for each time stamp
'''
Dictionary structure:
{time_stamp: {sensor_id_1: [sensor_data],
             sensor_id_2: [sensor_data], ...},
time_stamp_2: {sensor_id_1: [sensor_data], 
            sensor_id_2: [sensor_data], ...}, ...
'''
num_sensors = 54
from collections import defaultdict
data_dict = defaultdict(dict)
for dt in tqdm(X):
    if np.isnan(dt[1]):
        continue
    if int(dt[1]) < num_sensors:
        data_dict[int(dt[0])][int(dt[1])] = dt[2:]


# loop for creating the graph data for each time stamp
graphs = []
all_times = []
# change the line below to change the number of time stamps to be used for training
for time in tqdm(sorted(list(data_dict.keys()))[:5000]):
    all_times.append(time)
    #print(time)
    # some times are not multiple of 30, so skipping them
    #if time%30 != 0:
    #    continue
    sensor_data = np.zeros((num_sensors, 4))
    for sensor_id in data_dict[time]:
        try:
            # converting one indexing to zero indexing
            sensor_data[sensor_id-1] = (np.array(data_dict[time][sensor_id])-MIN_S[2:])/(MAX_S[2:]-MIN_S[2:])
        except:
            continue
    
    # creating the adjacency matrix
    adj_matrix = np.ones((num_sensors, num_sensors))

    #list of indices of sensors which are not present in the current time stamp
    a = [i for i in range(num_sensors) if i not in (np.array(list(data_dict[time].keys()))-1).tolist() ]

    # removing the edges from the adjacency matrix for those absent sensors
    for idx in a:
        for i in range(num_sensors):
            adj_matrix[idx][i] = 0
            adj_matrix[i][idx] = 0

    # removing self connections from the adjacency matrix because we want to predict the sensor data from other sensors
    np.fill_diagonal(adj_matrix, 0)
    # creating the edge list from the adjacency matrix with pyg graph edge list format
    temp = np.transpose(np.nonzero(adj_matrix)).reshape(1, -1)
    edge_list = np.array([np.array(temp[0][::2]) , np.array(temp[0][1::2])])

    # calculating the edge attributes for the graph
    edge_attr = []
    for idx in range(edge_list.shape[1]):
        fm, to = edge_list[0][idx]+1, edge_list[1][idx]+1
        edge_attr.append(math.sqrt((position[fm][0]-position[to][0])**2 + (position[fm][1]-position[to][1])**2))
    edge_attr = np.array(edge_attr)

    g = Data(x=torch.tensor(sensor_data, dtype=torch.float), 
             edge_index=torch.tensor(edge_list,dtype=torch.long), 
             y=torch.tensor(sensor_data, dtype=torch.float),
             edge_attr=torch.tensor(edge_attr.reshape(-1, 1), dtype=torch.float))
    
    # creating the train mask so that the loss is only calculated for the present sensors
    g.train_mask = np.array([False]*num_sensors)
    g.train_mask[np.array(list(data_dict[time].keys()))-1] = True
    g.train_mask = torch.tensor(g.train_mask)
 

    # creating the test mask so that the loss is not calculated for the absent sensors
    g.test_mask = np.array(([True]*num_sensors))
    g.test_mask[np.array(list(data_dict[time].keys()))-1] = False
    g.test_mask = torch.tensor(g.test_mask)

    graphs.append(g)

print(len(graphs))
#graphs = graphs[:10000]

# creaitng the dataloader for the graphs so that they can be used for batching and efficient training
loader = DataLoader(graphs, batch_size=10, shuffle=False)

# three models are used for comparison

class GCN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = GCNConv(num_sensors, 16)
        self.conv2 = GCNConv(16, 32)
        self.conv3 = GCNConv(32, 32)
        self.conv4 = GCNConv(32, 1)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index

        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        x = F.relu(x)
        x = self.conv3(x, edge_index)
        x = self.conv4(x, edge_index)
        x = torch.sigmoid(x)
        return x

class GAT(torch.nn.Module):
    """Graph Attention Network"""
    def __init__(self, dim_in=num_sensors,dim_h=64, dim_out=4, heads=8):
        super().__init__()
        self.gat1 = GATv2Conv(dim_in, dim_h, heads=heads)
        self.bn1 = nn.BatchNorm1d(dim_h*heads)
        self.gats = nn.ModuleList(
            [
                GATv2Conv(dim_h*heads, dim_h*heads)
                for _ in range(2)
             ]
        )
        self.bn2s = nn.ModuleList(
            [
                nn.BatchNorm1d(dim_h*heads)
                for _ in range(2)
            ]
        )
        self.gat2 = GATv2Conv(dim_h*heads, dim_out, heads=1)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        #print(x.shape)
        h = self.gat1(x, edge_index)
        #print(h.shape)
        #h = self.bn1(h)
        h = F.relu(h)
        #print(h.shape)
        #for gat, bn in zip(self.gats, self.bn2s):
        #    h = gat(h, edge_index)
        #    h = bn(h)
        #    h = F.elu(h)
        #h = F.elu(h)

        h , att_weights = self.gat2(h, edge_index, return_attention_weights=True)
        #h = torch.sigmoid(h)
        #print(h.shape)
        return h, att_weights


class GAT_V2(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.gat1 = GATv2Conv(4, 120, heads=8)
        self.gat2 = GATv2Conv(120*8, 4, heads=1)
        #self.conv1 = GCNConv(data.num_node_features, 120)
        #self.linear = nn.Linear(120, 5)
        #self.sigmoid = nn.Sigmoid()

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = self.gat1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x)
        x = self.gat2(x, edge_index) 
        #logits, attention_weights = x
        return x

100%|██████████| 5000/5000 [00:10<00:00, 497.18it/s]

5000


In [37]:
idx = 2017
print(graphs[idx].train_mask)
print(sorted(list(data_dict[(idx+1)*30].keys())))



tensor([ True, False,  True,  True, False,  True,  True,  True,  True,  True,
        False,  True, False,  True, False,  True, False,  True,  True,  True,
         True,  True,  True,  True, False,  True, False, False, False,  True,
         True, False,  True, False,  True, False,  True, False, False, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True, False])
[1, 3, 4, 6, 7, 8, 9, 10, 12, 14, 16, 18, 19, 20, 21, 22, 23, 24, 26, 30, 31, 33, 35, 37, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 53]


In [30]:
(2016+1)*30

60510

In [ ]:
[1, 3, 4, 6, 7, 8, 9, 10, 12, 14, 16, 18, 19, 20, 21, 22, 23, 24, 26, 30, 31, 33, 35, 37, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 53]
tensor([False, False,  True,  True, False, False,  True, False,  True,  True,
         True, False, False,  True, False,  True, False,  True,  True,  True,
         True,  True, False,  True,  True,  True, False, False,  True,  True,
         True, False, False, False,  True,  True,  True, False, False,  True,
        False,  True,  True, False,  True,  True,  True,  True, False,  True,
         True,  True, False, False])
3, 4, 7, 9, 10, 11, 14, 16, 18, 19, 20, 21, 22, 24, 25, 26, 29, 30, 31, 35, 36, 37, 40, 42, 43, 45, 46, 47, 48, 50, 51, 52

In [41]:
def train_node_classifier(model, graphs, optimizer, criterion, n_epochs=100):

    for epoch in tqdm(range(1, n_epochs + 1)):
        total_loss = 0

        for graph in tqdm(graphs):
            model.train()
            optimizer.zero_grad()
            #print("before comes", graph.x.shape, graph.y.shape, graph.train_mask.shape, graph.edge_index)
            out = model(graph)
            #print("comes", graph.x.shape,out.shape, graph.y.shape, graph.train_mask.shape)
            loss = criterion(out[graph.train_mask] , graph.y[graph.train_mask])
            #print(loss)
            if math.isnan(loss.item()):
                print(epoch,graph.train_mask, out[graph.train_mask], graph.y[graph.train_mask], criterion(out[graph.train_mask], graph.y[graph.train_mask]))
                print("######### SHOULD NOT HAPPEN ######### ", loss)
                break
                #print(graph.x, graph.train_mask)
            #print(loss)
            total_loss+=loss.item()
            loss.backward()
            optimizer.step()
        
        print(f'Epoch: {epoch:03d}, Train Loss: {total_loss:.3f}')

    return model

# redundant code (can be removed but kept for reference)
adj_matrix = np.ones((num_sensors, num_sensors))
np.fill_diagonal(adj_matrix, 0)
temp = np.transpose(np.nonzero(adj_matrix)).reshape(1, -1)
edge_list = np.array([np.array(temp[0][::2]) , np.array(temp[0][1::2])])

edge_attr = []
for idx in range(edge_list.shape[1]):
    fm, to = edge_list[0][idx]+1, edge_list[1][idx]+1
    edge_attr.append(math.sqrt((position[fm][0]-position[to][0])**2 + (position[fm][1]-position[to][1])**2))
edge_attr = np.array(edge_attr)

out_final = []
def eval_node_classifier(model, graphs):
    model.eval()
    with torch.no_grad():
        for idx, graph in tqdm(enumerate(graphs)):
            g = copy.deepcopy(graph)    
            g.edge_index = torch.tensor(edge_list,dtype=torch.long)
            g.edge_attr = torch.tensor(edge_attr.reshape(-1, 1), dtype=torch.float)
            out = model(g)
            out_list = out.detach().numpy().tolist()
            time = all_times[idx]
            for i in range(num_sensors):
                # we want a prediction for each sensor
                if not graph.train_mask[i]:
                    # if this sensor is not in the training set, we want to predict and use the imputed value
                    out_final.append([time, i+1]+out_list[i])
                else:
                    try:
                        # if this sensor is in the training set, we want to use the ground truth value
                        out_final.append([time, i+1]+((np.array(data_dict[time][i+1])-MIN_S[2:])/(MAX_S[2:]-MIN_S[2:])).tolist())
                    except Exception as e:
                        # print error e with trace
                        print(str(e))
                        print((idx+1)*30)
                        print(sorted(list(data_dict[(idx+1)*30].keys())))
                        print(g.train_mask)
                        print(g.test_mask)



#model = GCN().to('cpu')
#model = GAT().to('cpu')
model = GAT_V2().to('cpu')
#optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-4)

#criterion = nn.CrossEntropyLoss()
#criterion = nn.L1Loss()
#criterion = nn.BCEWithLogitsLoss()
#criterion = nn.BCELoss()
criterion = nn.MSELoss()
#model = train_node_classifier(model, loader, optimizer, criterion, n_epochs=10)

model.eval()

eval_node_classifier(model, graphs)

# save out_final to csv with column names
mod_df = pd.DataFrame(out_final, columns=["time", "nodeid", "temperature" ,"humidity", "light", "voltage"])
mod_df.to_csv('modified_env.csv', index=False)

'''
30,1,0.20009765028953552,0.0059858085587620735,0.7404278516769409,-0.0762353166937828
30,2,0.2406468242406845,0.01273853424936533,0.838738203048706,-0.046470265835523605
30,3,0.1382274133896898,0.988967344623328,0.027390438247011956,0.8541260865461349
30,4,0.2236645221710205,-0.018838858231902122,0.7683352828025818,-0.02886117435991764
30,5,0.214375302195549,-0.050112172961235046,0.812414824962616,-0.05435218662023544
30,6,0.1387359423352706,0.9889371603446336,0.06573705179282868,0.8388215635376892
30,7,0.2642294466495514,-0.007743816822767258,0.8069591522216797,-0.06117755547165871
'''

2323it [00:28, 82.38it/s]


KeyboardInterrupt: 

In [5]:
graphs[0].train_mask

tensor([False, False,  True, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False,  True,  True,
        False, False, False,  True,  True,  True,  True, False, False, False,
         True, False, False,  True, False, False, False, False, False,  True,
        False, False,  True, False, False, False, False, False, False, False,
        False, False, False, False])

In [48]:
import pandas as pd
from torch_geometric.data import Data
import numpy as np
import torch
import torch.nn as nn

from torch_geometric.nn import GCNConv
import torch.nn.functional as F
from tqdm import tqdm
import math
from torch_geometric.nn import GCNConv, GATv2Conv
from torch_geometric.loader import DataLoader

torch.manual_seed(12345)

df = pd.read_csv("df_env.csv")
all_ids = df.ID.to_list()
df = df.drop(columns=['ID'])
print(df.shape)
df_list = df.values.tolist()

#df = df.dropna(how='all')
df = df.apply(lambda x: (x - x.min()) / (x.max() - x.min()))

num_cols = 24

(3843, 24)
